
import java.awt.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        layar = new javax.swing.JLabel();
        Layar = new ugambar();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mn_Input = new javax.swing.JMenu();
        Mn_DataBarang = new javax.swing.JMenuItem();
        Mn_StokBarang = new javax.swing.JMenuItem();
        Mn_LihatStok = new javax.swing.JMenu();
        Mn_Logout = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME");
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        layar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(layar);

        javax.swing.GroupLayout LayarLayout = new javax.swing.GroupLayout(Layar);
        Layar.setLayout(LayarLayout);
        LayarLayout.setHorizontalGroup(
            LayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LayarLayout.setVerticalGroup(
            LayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Layar);

        Mn_Input.setText("Input");
        Mn_Input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mn_InputMouseClicked(evt);
            }
        });
        Mn_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_InputActionPerformed(evt);
            }
        });

        Mn_DataBarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Mn_DataBarang.setText("Data Barang");
        Mn_DataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_DataBarangActionPerformed(evt);
            }
        });
        Mn_Input.add(Mn_DataBarang);

        Mn_StokBarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Mn_StokBarang.setText("Stok Barang");
        Mn_StokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_StokBarangActionPerformed(evt);
            }
        });
        Mn_Input.add(Mn_StokBarang);

        jMenuBar1.add(Mn_Input);

        Mn_LihatStok.setText("Lihat Stok");
        Mn_LihatStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mn_LihatStokMouseClicked(evt);
            }
        });
        Mn_LihatStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_LihatStokActionPerformed(evt);
            }
        });
        jMenuBar1.add(Mn_LihatStok);

        Mn_Logout.setText("Logout");
        Mn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mn_LogoutMouseClicked(evt);
            }
        });
        Mn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_LogoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(Mn_Logout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mn_LogoutActionPerformed

    private void Mn_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mn_LogoutMouseClicked
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Anda Yakin Logout?", "PERINGATAN!!!",JOptionPane.YES_NO_OPTION);
        if (option == 0){
            Login A = new Login();
            A.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_Mn_LogoutMouseClicked

    private void Mn_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mn_InputActionPerformed

    private void Mn_InputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mn_InputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Mn_InputMouseClicked

    private void Mn_DataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_DataBarangActionPerformed
        // TODO add your handling code here:
        MenuDataBarang Mn_DataBarang = new MenuDataBarang();
        Layar.add(Mn_DataBarang);
        Mn_DataBarang.setVisible(true);
    }//GEN-LAST:event_Mn_DataBarangActionPerformed

    private void Mn_StokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_StokBarangActionPerformed
        // TODO add your handling code here:
        MenuStokBarang Mn_StokBarang = new MenuStokBarang();
        Layar.add(Mn_StokBarang);
        Mn_StokBarang.setVisible(true);
    }//GEN-LAST:event_Mn_StokBarangActionPerformed

    private void Mn_LihatStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_LihatStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mn_LihatStokActionPerformed

    private void Mn_LihatStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mn_LihatStokMouseClicked
        // TODO add your handling code here:
        MenuLihatStok Mn_LihatStok = new MenuLihatStok();
        Layar.add(Mn_LihatStok);
        Mn_LihatStok.setVisible(true);
    }//GEN-LAST:event_Mn_LihatStokMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Layar;
    private javax.swing.JMenuItem Mn_DataBarang;
    private javax.swing.JMenu Mn_Input;
    private javax.swing.JMenu Mn_LihatStok;
    private javax.swing.JMenu Mn_Logout;
    private javax.swing.JMenuItem Mn_StokBarang;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel layar;
    // End of variables declaration//GEN-END:variables
}
