
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class MenuDataBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuDataBarang
     */
    public MenuDataBarang() {
        initComponents();
        tampilTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cb_Kategori = new javax.swing.JComboBox<>();
        In_KodeBarang = new javax.swing.JTextField();
        In_NamaBarang = new javax.swing.JTextField();
        In_Harga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_Barang = new javax.swing.JTable();
        Bt_Tambah = new javax.swing.JButton();
        Bt_Hapus = new javax.swing.JButton();
        Bt_Edit = new javax.swing.JButton();
        Bt_Clear = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("DATA BARANG");

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Kategori");

        jLabel4.setText("Harga");

        Cb_Kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kategori", "Makanan", "Minuman" }));
        Cb_Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_KategoriActionPerformed(evt);
            }
        });

        Tb_Barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama", "Kategori", "Harga"
            }
        ));
        Tb_Barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_BarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_Barang);

        Bt_Tambah.setText("Tambah");
        Bt_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_TambahActionPerformed(evt);
            }
        });

        Bt_Hapus.setText("Hapus");
        Bt_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_HapusActionPerformed(evt);
            }
        });

        Bt_Edit.setText("Ubah");
        Bt_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_EditActionPerformed(evt);
            }
        });

        Bt_Clear.setText("Bersih");
        Bt_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(In_Harga, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(Cb_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(In_KodeBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(In_NamaBarang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bt_Tambah, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bt_Edit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bt_Hapus, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bt_Clear, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(In_KodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bt_Tambah))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(In_NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cb_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(In_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bt_Edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bt_Clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bt_Hapus)))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {In_Harga, In_KodeBarang, In_NamaBarang});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cb_KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_KategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cb_KategoriActionPerformed

    private void Bt_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_HapusActionPerformed
        // TODO add your handling code here:
        String KodeBarang = In_KodeBarang.getText();
        String NamaBarang = In_NamaBarang.getText();
        String Kategori = (String) Cb_Kategori.getSelectedItem();
        String Harga = In_Harga.getText();
        
        if(KodeBarang.equals("")||NamaBarang.equals("")||Kategori.equals("Pilih Kategori")||Harga.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih Data yang ingin dihapus!");
        /*if(KodeBarang.equals("")){
            JOptionPane.showMessageDialog(null, "ISI dulu kodenya");
        }else if(NamaBarang.equals("")){
            JOptionPane.showMessageDialog(null, "Ini teh barang apa sih?");
        }else if(Kategori.equals("Pilih Kategori")){
            JOptionPane.showMessageDialog(null, "PILIH Kategori lah KAWAN");
        }else if(Harga.equals("")){
            JOptionPane.showMessageDialog(null, "Harganya berapa?");*/
        }else{
            try{
                //1. Querry
                String deleteSQL = "DELETE FROM tb_stok WHERE kode_barang = '"+KodeBarang+"'";
                //2. Koneksi
                Connection VConn = (Connection)KoneksiDB.configDB();
                //3. Statement
                PreparedStatement S = VConn.prepareStatement(deleteSQL);
                //4. Eksekusi Querry
                S.execute();
                //5. Menampilkan Notif Berhasil
                int option = JOptionPane.showConfirmDialog(null, "Anda yakin Menghapus Data?", "PERINGATAN", JOptionPane.YES_NO_OPTION);
                JOptionPane.showMessageDialog(null, "Hapus Data " +KodeBarang+ " Berhasil!");
                tampilTable();
                clearText();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Hapus Data Gagal!");
                JOptionPane.showMessageDialog(this, e.getMessage());  
            }
        }
    }//GEN-LAST:event_Bt_HapusActionPerformed

    private void Bt_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_TambahActionPerformed
        // TODO add your handling code here:
        String KodeBarang = In_KodeBarang.getText();
        String NamaBarang = In_NamaBarang.getText();
        String Kategori = (String) Cb_Kategori.getSelectedItem();
        String Harga = In_Harga.getText();
        int Stok = 0;
        
        if(KodeBarang.equals("")){
            JOptionPane.showMessageDialog(null, "Isi Dulu Kodenya!");
        }else if(NamaBarang.equals("")){
            JOptionPane.showMessageDialog(null, "Ini teh Barang Apa Sih?");
        }else if(Kategori.equals("Pilih Kategori")){
            JOptionPane.showMessageDialog(null, "Pilih Kategori lah Kawan!");
        }else if(Harga.equals("")){
            JOptionPane.showMessageDialog(null, "Harganya Berapa?");
        }else{
            try {
                String KirimSQL = "INSERT INTO tb_stok (kode_barang, nama, kategori, harga, stok) VALUES ('"+KodeBarang+"','"+NamaBarang+"','"+Kategori+"','"+Harga+"','"+Stok+"')";
                Connection VConn = (Connection)KoneksiDB.configDB();
                PreparedStatement S = VConn.prepareStatement(KirimSQL);
                S.execute();
                JOptionPane.showMessageDialog(null, "Tambah Data Barang Berhasil!");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Tambah Data Barang Gagal!");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            tampilTable();
            clearText();
        }
    }//GEN-LAST:event_Bt_TambahActionPerformed

    private void Bt_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_EditActionPerformed
        // TODO add your handling code here:
        String KodeBarang = In_KodeBarang.getText();
        String NamaBarang = In_NamaBarang.getText();
        String Kategori = (String) Cb_Kategori.getSelectedItem();
        String Harga = In_Harga.getText();
        
        if(KodeBarang.equals("")||NamaBarang.equals("")||Kategori.equals("Pilih Kategori")||Harga.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih Data yang ingin diubah!");
        /*if(KodeBarang.equals("")){
            JOptionPane.showMessageDialog(null, "ISI dulu kodenya");
        }else if(NamaBarang.equals("")){
            JOptionPane.showMessageDialog(null, "Ini teh barang apa sih?");
        }else if(Kategori.equals("Pilih Kategori")){
            JOptionPane.showMessageDialog(null, "PILIH Kategori lah KAWAN");
        }else if(Harga.equals("")){
            JOptionPane.showMessageDialog(null, "Harganya berapa?");
        }else if(KodeBarang.equals("") && NamaBarang.equals("") && Kategori.equals("Pilih Kategori") && Harga.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih dulu datanya");*/ 
        }else{
            try {
                    String EditSQL = "UPDATE tb_stok SET nama = '"+NamaBarang+"', kategori = '"+Kategori+"', harga = '"+Harga+"' WHERE kode_barang = '"+KodeBarang+"'";
                    Connection VConn = (Connection)KoneksiDB.configDB();
                    PreparedStatement S = VConn.prepareStatement(EditSQL);
                    S.execute();
                    JOptionPane.showMessageDialog(null, "Ubah Data" +KodeBarang+ "Berhasil!");
                    tampilTable();
                    clearText();
                }catch (Exception e){
                    //if (e.getMessage()=){
                        
                    //}
                    JOptionPane.showMessageDialog(null, "Ubah Data Gagal!");
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
        }
    }//GEN-LAST:event_Bt_EditActionPerformed

    private void Bt_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ClearActionPerformed
        // TODO add your handling code here:
        clearText();
    }//GEN-LAST:event_Bt_ClearActionPerformed

    private void Tb_BarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_BarangMouseClicked
        // TODO add your handling code here:
        int baris = Tb_Barang.rowAtPoint(evt.getPoint());
        //int kolom = Tb_Barang.columnAtPoint(evt.getPoint());
        
        String KodeBarang = Tb_Barang.getValueAt(baris, 0).toString();
        String NamaBarang = Tb_Barang.getValueAt(baris, 1).toString();
        String Kategori = Tb_Barang.getValueAt(baris, 2).toString();
        String Harga = Tb_Barang.getValueAt(baris, 3).toString();
        
        In_KodeBarang.setText(KodeBarang);
        In_NamaBarang.setText(NamaBarang);
        Cb_Kategori.setSelectedItem(Kategori);
        In_Harga.setText(Harga);
    }//GEN-LAST:event_Tb_BarangMouseClicked

    private  void tampilTable(){
        //membuat objek model di tabel
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Kode Barang");
        tb.addColumn("Nama");
        tb.addColumn("Kategori");
        tb.addColumn("Harga");

        try {
            // pen biar ada RP nya tapi error pas kirim data
            //String IDR = "Rp";
            // Query 
            String query = "SELECT * FROM tb_stok";
            // Fungsi Koneksi
            java.sql.Connection koneksi = (Connection)KoneksiDB.configDB();
            // Kirim parameter fungsi java ke sql
            java.sql.Statement s = koneksi.createStatement();
            // eksekusi query
            java.sql.ResultSet r = s.executeQuery(query);
            // looping 
            while (r.next()){
                tb.addRow(new Object[]{
                   r.getString(1), r.getString(2), r.getString(3),/*IDR +*/ r.getInt(4)
                });
                Tb_Barang.setModel(tb);
            }
        }catch (SQLException e){

        }
    }
    
    private void clearText(){
        In_KodeBarang.setText(" ");
        In_NamaBarang.setText(" ");
        Cb_Kategori.setSelectedIndex(0);
        In_Harga.setText(" ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Clear;
    private javax.swing.JButton Bt_Edit;
    private javax.swing.JButton Bt_Hapus;
    private javax.swing.JButton Bt_Tambah;
    private javax.swing.JComboBox<String> Cb_Kategori;
    private javax.swing.JTextField In_Harga;
    private javax.swing.JTextField In_KodeBarang;
    private javax.swing.JTextField In_NamaBarang;
    private javax.swing.JTable Tb_Barang;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
